<?php

declare(strict_types=1);

/**
 * @var \JcElectronics\ExactOrders\Block\Adminhtml\Order\View\Attachments $block
 * @var \Magento\Framework\Escaper $escaper
 */

$attachments = $block->getAttachments();
?>

<section class="admin__page-section">
    <div class="admin__page-section-title">
        <span class="title"><?= $escaper->escapeHtml(__('Order Attachments')) ?></span>
    </div>
    <div class="admin__page-section-content">
        <?php if (count($attachments)):?>
            <table>
                <?php /** @var \JcElectronics\ExactOrders\Api\Data\AttachmentInterface $attachment */ ?>
                <?php foreach ($attachments as $attachment): ?>
                <tr>
                    <td>
                        <a href="<?= $escaper->escapeUrl($block->getUrl('exactorders/attachment/view', ['id' => $attachment->getId()])) ?>">
                            <?= $escaper->escapeHtml($attachment->getFileName()) ?>
                        </a>
                    </td>
                </tr>
                <?php endforeach; ?>
            </table>
        <?php else: ?>
            <?= $escaper->escapeHtml(__('There are no attachments.')) ?>
        <?php endif ?>
    </div>
</section>
